name: Build

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - "dev/**"
      - "alpha/**"
      - "release/**"

permissions:
  contents: read
  issues: write

jobs:
  publication:
    uses: kungfu-systems/buildchain/.github/workflows/publication-artifact.yml@4147226415630a0cba6bb3be56f32410fb56c2b1
    with:
      buildchain-ref: 4147226415630a0cba6bb3be56f32410fb56c2b1
      buildchain-contract-lock-path: .buildchain/contract-lock.json
      toolchain-type: config
      verify-command: make check
      artifact-name: "paper-kfd-machine-life-roadmap"
