name: Build

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - "dev/**"
      - "alpha/**"
      - "release/**"

permissions:
  contents: read
  issues: write

jobs:
  publication:
    uses: kungfu-systems/buildchain/.github/workflows/publication-artifact.yml@7c61f08514bfc29a8653c4efb4768cbca13da742
    with:
      buildchain-ref: 7c61f08514bfc29a8653c4efb4768cbca13da742
      buildchain-contract-lock-path: .buildchain/contract-lock.json
      toolchain-type: config
      verify-command: make check
      artifact-name: "paper-kfd-machine-life-roadmap"
