name: Build

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - "dev/**"
      - "alpha/**"
      - "release/**"

permissions:
  contents: read
  issues: write

jobs:
  publication:
    uses: kungfu-systems/buildchain/.github/workflows/publication-artifact.yml@2cd4e117742ca39fddd43e4244d01581cae75556
    with:
      buildchain-ref: 2cd4e117742ca39fddd43e4244d01581cae75556
      buildchain-contract-lock-path: .buildchain/contract-lock.json
      toolchain-type: config
      verify-command: make check
      artifact-name: "paper-kfd-machine-life-roadmap"
